[package]
name = "xtask-crdgen"
version.workspace = true
edition.workspace = true

[dependencies]
krangle-operator = { path = "../krangle-operator" }
kube.workspace = true
serde_yaml.workspace = true
