[package]
name = "krangle-operator"
version.workspace = true
edition.workspace = true

[dependencies]
kube.workspace = true
k8s-openapi.workspace = true
schemars = "0.8.22"
serde = { version ="1.0.219", features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
