[package]
name = "swkotor-mod"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version="0.59.0", features=["Win32_Foundation", "Win32_System_SystemServices"] }
